# Generated by Django 5.2.6 on 2025-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
