# Generated by Django 5.2.6 on 2025-09-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('fromaddress', models.EmailField(max_length=254)),
                ('toaddress', models.TextField()),
            ],
        ),
    ]
